### ISSUE TITLE
List place or address from my country by search, not showing

### ISSUE THREAD

**Issue by amaydiam** [SchibstedSpain/Leku#105]
Hello, I'm from indonesia. I use this library for my apps. But i get something bugs. **List place or address from my country by search, not showing**. I type "Pamulang", this is place name in my country, but now show.

This is my code:
LocationPickerActivity.Builder pick = new LocationPickerActivity.Builder()
                .withGeolocApiKey(getString(R.string.google_maps_key))
                .withStreetHidden()
                .withCityHidden()
                .withSearchZone("es_ES")
                .withZipCodeHidden()
                .withSatelliteViewHidden();

so how to solve it ? thanks

**Comment by ferranpons** [comment]
@amaydiam As I see you are using the Spain search zone. So you have to use your country code, so you have to change this line:

> .withSearchZone("es_ES")

**Comment by ferranpons** [comment]
@amaydiam please could you confirm that this solution is working for you?

I'm closing this issue. If you are still experiencing this problem please reopen the issue.

Many thanks for reporting it. 😉
