### ISSUE TITLE
Locale support PRs not working for locales not existing in java.util.Locale

### ISSUE THREAD

**Issue by ahaverty** [SchibstedSpain/Leku#109]
## Description
The recent PRs for locale support don't appear to be working. It looks like we are trying to create Locale object's from country codes and then later querying the locale.getCountry()
However, this will only work for countries listed in java.util.Locale (Which is a very small amount).
For example, when I followed the latest PR format to add support for Ireland (IE), `LocationPickerActivity.retrieveLocationFromZone()` creates `new Locale("IE")` but then later queries `locale.getCountry()` in `CountryLocaleRect.getLowerLeftFromZone()` which actually returns `null`

I'm going to personally go with a hack workaround for now, but I feel like we should come up with a better solution for locales? Surely some library is already doing this (getting lat/lng bounds) for the majority of countries?

<img width="615" alt="screen shot 2017-08-19 at 00 05 47" src="https://user-images.githubusercontent.com/2920947/29480700-3c5f2456-8472-11e7-8743-4ee7f1e4f3ed.png">

## Info Required
- Which version of the library do you actually use?
v3.4.3

**Comment by ferranpons** [comment]
@ahaverty Thanks for your report. It's true, it's not working correctly.

The PR #112 Solves the issue. I'll create a new version with the fix today.

Sorry for the inconvenience. 🙏

**Comment by ferranpons** [comment]
@ahaverty new version 3.4.5 is available. If you still have the same problem please reopen this issue.

Many thanks for your report!
