### ISSUE TITLE
Option to disable voice search (enhancement)

### ISSUE THREAD

**Issue by cotfas** [SchibstedSpain/Leku#110]
## Description

Option into the Builder to disable voice search

**and another option to disable the Coordinates box, and only to show the result box when the address is selected (valid address)

## Info Required

- Which version of the library do you actually use?

  compile 'com.schibstedspain.android:leku:3.4.3'

- Do you have the localization permission granted?

Yes!

- Are you sending parameters to the activity through the bundle?

With builder and sending the intent to the activity.

- Could you describe what are the actions do you make to raise that error?

Is not an error, more like an enhancement.

- Android monitor shows any log related to the library when the error is shown?

Is not an error, more like an enhancement.

- Any other thing that could help me to reproduce the error?

Is not an error, more like an enhancement.

**Comment by ferranpons** [comment]
@cotfas thanks for your suggestion! I'll create the option as soon as I can. 😉

**Comment by cotfas** [comment]
Hi,

Thanks

Also, an option to customize from outside (intent) the searchView text hint
:D

Thank you

**Comment by ferranpons** [comment]
Hi @cotfas !

This will be available in the next release version 5.0.0 that will be released soon.

Many thanks!

**Comment by ferranpons** [comment]
New release version 5.0.0 now available for download. I'm closing this issue because it's solved with the latest version. If it fails again please reopen the issue. Many thanks for reporting it and for using this library!
