### ISSUE TITLE
Xiaomi, Walton Not showing current location

### ISSUE THREAD

**Issue by AhmadullahSaikat** [SchibstedSpain/Leku#115]
Not showing current location & always show me the co-ordinates... Please fix this issue for those devices...

I am using 3.4.5 version...

**Comment by ferranpons** [comment]
@AhmadullahSaikat which devices?

**Comment by AhmadullahSaikat** [comment]
1. Xiaomi
2. Walton
Now for walton it's ok...
Sometimes not showing current location...  But today it shows ok for [walton] device...
what's the reason?

**Comment by ferranpons** [comment]
@AhmadullahSaikat @sagarikadas91 Could be a problem with the version of Play Services for those devices or even the Geocoder service not working properly (that fails a lot).

Have you tried the Geocoding API Fallback option? As a solution, you could try to use that feature to avoid this kind of issues. You could check the documentation [here](https://github.com/SchibstedSpain/Leku#geocoding-api-fallback)

**Comment by ferranpons** [comment]
@AhmadullahSaikat @sagarikadas91 Any news on that?

I'm going to close it. If you're still experiencing this issue please re-open it. Many thanks.
