### ISSUE TITLE
onDestroy is calling by startActivityForResult

### ISSUE THREAD

**Issue by bewithdhanu** [SchibstedSpain/Leku#116]
## Description
onDestroy is calling by startActivityForResult, how to avoid calling OnDestroy
## Info Required

- Which version of the library do you actually use?
3.4.5
- Do you have the localization permission granted?
Yes
- Are you sending parameters to the activity through the bundle?
No
- Could you describe what are the actions do you make to raise that error?

- Android monitor shows any log related to the library when the error is shown?

 Any other thing that could help me to reproduce the error?

**Comment by ferranpons** [comment]
@bewithdhanu that is a behavior of Android itself. The library is not doing anything in "onDestroy" event. It's possible that if you're using an old device with an old api version could make that happen. You would have to bypass that behavior somehow using the "requestcode" and the "resultcode" that onActivityResult receives.

Anyway, we are going to refactor the picker activity to be able to not use "startActivityForResult".

**Comment by bewithdhanu** [comment]
Thank You...:-)
