### ISSUE TITLE
Error NoClassDefFoundError in using the LocationPickerActivity

### ISSUE THREAD

**Issue by lprudhomme** [SchibstedSpain/Leku#136]
## Description
I'd like to use your activity but when my app starts the activty I got the error message below:

I/AppCompatViewInflater: app:theme is now deprecated. Please move to using android:theme instead.
I/art: Rejecting re-init on previously-failed class java.lang.Class<com.schibstedspain.leku.geocoder.-$$Lambda$GoogleGeocoderDataSource$jvAbfK7I4pkKhtcvPMA6WwArpsw>
I/art: Rejecting re-init on previously-failed class java.lang.Class<com.schibstedspain.leku.geocoder.-$$Lambda$GoogleGeocoderDataSource$jvAbfK7I4pkKhtcvPMA6WwArpsw>
I/art: Rejecting re-init on previously-failed class java.lang.Class<com.schibstedspain.leku.geocoder.-$$Lambda$GoogleGeocoderDataSource$jvAbfK7I4pkKhtcvPMA6WwArpsw>
A/art: art/runtime/thread.cc:1336] No pending exception expected: java.lang.NoClassDefFoundError: com.schibstedspain.leku.geocoder.-$$Lambda$GoogleGeocoderDataSource$jvAbfK7I4pkKhtcvPMA6WwArpsw
A/art: art/runtime/thread.cc:1336]   at java.lang.Class dalvik.system.DexFile.defineClassNative(java.lang.String, java.lang.ClassLoader, java.lang.Object) (DexFile.java:-2)
A/art: art/runtime/thread.cc:1336]   at java.lang.Class dalvik.system.DexFile.defineClass(java.lang.String, java.lang.ClassLoader, java.lang.Object, java.util.List) (DexFile.java:226)
A/art: art/runtime/thread.cc:1336]   at java.lang.Class dalvik.system.DexFile.loadClassBinaryName(java.lang.String, java.lang.ClassLoader, java.util.List) (DexFile.java:219)
A/art: art/runtime/thread.cc:1336]   at java.lang.Class dalvik.system.DexPathList.findClass(java.lang.String, java.util.List) (DexPathList.java:338)
A/art: art/runtime/thread.cc:1336]   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:54)
A/art: art/runtime/thread.cc:1336]   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:511)
A/art: art/runtime/thread.cc:1336]   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:469)
A/art: art/runtime/thread.cc:1336]   at void com.schibstedspain.leku.LocationPickerActivity.setUpMainVariables() (LocationPickerActivity.java:164)
A/art: art/runtime/thread.cc:1336]   at void com.schibstedspain.leku.LocationPickerActivity.onCreate(android.os.Bundle) (LocationPickerActivity.java:140)
A/art: art/runtime/thread.cc:1336]   at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:6285)
A/art: art/runtime/thread.cc:1336]   at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1108)
A/art: art/runtime/thread.cc:1336]   at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2417)
A/art: art/runtime/thread.cc:1336]   at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2524)
A/art: art/runtime/thread.cc:1336]   at void android.app.ActivityThread.access$900(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:154)
A/art: art/runtime/thread.cc:1336]   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1391)
A/art: art/runtime/thread.cc:1336]   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
A/art: art/runtime/thread.cc:1336]   at void android.os.Looper.loop() (Looper.java:234)
A/art: art/runtime/thread.cc:1336]   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:5526)
A/art: art/runtime/thread.cc:1336]   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
A/art: art/runtime/thread.cc:1336]   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:726)
A/art: art/runtime/thread.cc:1336]   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:616)
A/art: art/runtime/thread.cc:1336] 
A/art: art/runtime/barrier.cc:90] Check failed: count_ == 0 (count_=-1, 0=0) Attempted to destroy barrier with non zero count
A/art: art/runtime/runtime.cc:370] Runtime aborting --- recursively, so no thread-specific detail!
A/art: art/runtime/runtime.cc:370] 
A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 18265 (ookal.mapsample)

The build.graddle file contains:
apply plugin: 'com.android.application'

repositories {
    mavenCentral()
    maven {
        url 'https://maven.google.com/'
        name 'Google'
    }
}
android {
    compileSdkVersion 27
    buildToolsVersion '27.0.3'
    defaultConfig {
        applicationId "com.glookal.mapsample"
        minSdkVersion 19
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

        multiDexEnabled true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    dexOptions {
        jumboMode = true
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:27.0.2'
    implementation 'com.google.android.gms:play-services-maps:11.8.0'
    implementation 'com.google.android.gms:play-services-places:11.8.0'
    implementation 'com.google.android.gms:play-services-location:11.8.0'
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    implementation 'com.android.support:design:27.0.2'
    implementation ('com.schibstedspain.android:leku:3.7.0')
}

## Info Required

- Which version of the library do you actually use?
3.7.0

- Do you have the localization permission granted?
Yes

- Are you sending parameters to the activity through the bundle?
No

- Could you describe what are the actions do you make to raise that error?
The error appears when my app call the activity via the intent

- Android monitor shows any log related to the library when the error is shown?
Yes, see above

- Any other thing that could help me to reproduce the error?
?

**Comment by ferranpons** [comment]
Hi @lprudhomme!

Are you sure that you have correctly implemented multidex? I mean, do you extend your application class with `MultiDexApplication` or do you use the method `MultiDex.install(this);` on your `attachBaseContext` method? Or use the `android:name="android.support.multidex.MultiDexApplication"` on your manifest?

Also I don't see the dependency compile for multidex in your build.gradle.

**Comment by lprudhomme** [comment]
Hi,
No, I did not use any of your proposals. I followed strictly what you described on your site. Could you give me more details on how to properly configure multidex (extract from manifest or build.gradle, for example)?
Thanks for your help

**Comment by ferranpons** [comment]
@lprudhomme to configure it you could check the official android documentation for multidex:

[https://developer.android.com/studio/build/multidex.html](https://developer.android.com/studio/build/multidex.html)

**Comment by lprudhomme** [comment]
Thanks. I followed the documentation and the error changed :(
java.lang.NoClassDefFoundError: Failed resolution of: Lpl/charmas/android/reactivelocation2/ReactiveLocationProvider;
                                                                         at com.schibstedspain.leku.LocationPickerActivity.setUpMainVariables(LocationPickerActivity.java:166)
                                                                         at com.schibstedspain.leku.LocationPickerActivity.onCreate(LocationPickerActivity.java:140)

Did I forgot something else ?

**Comment by ferranpons** [comment]
@lprudhomme I'm sorry to hear that. 😞 

Have you tried to make a clean and rebuild project? Because could be a problem with the build cache.

Does it happen on debug or release flavour? Are you using proguard?

**Comment by lprudhomme** [comment]
Sorry, for the delay.
I tried to clean and re-built project. Nothing changed, the error remained.
To answer to your questions, it's a release version running on a device and I don't use proguard.
Sorry but I cannot use your project in my app. It's very shame :(

**Comment by ferranpons** [comment]
@lprudhomme you are using proguard since you have these lines in your build.gradle file:

```
buildTypes {
    release {
        minifyEnabled false
        proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
    }
}
```

So probably you should try to add this lines to your proguard-rules.pro file:

```
-dontwarn pl.charmas.android.reactivelocation2.**
-keep interface pl.charmas.android.reactivelocation2.** { *; }
-keep class pl.charmas.android.reactivelocation2.** { *; }
```

**Comment by ferranpons** [comment]
@lprudhomme do you have any news about this? Thanks!

**Comment by ferranpons** [comment]
@lprudhomme I'm closing the issue. I assume that you found a solution or you are not using the library any more. If you are still experiencing this problem please reopen the issue to try to find a solution. :)

**Comment by mptrista** [comment]
@ferranpons Issue still exists
