### ISSUE TITLE
Search Location AutoComplete is not working in pakistan

### ISSUE THREAD

**Issue by ahmedjamshed** [SchibstedSpain/Leku#141]
## Description

**Search Location Autocomplete is not working in Pakistan with locale 'en_PK'. Only very few locations are discoverable.**

## Info Required

- Which version of the library do you actually use?

**implementation ('com.schibstedspain.android:leku:3.5.0') {
        exclude group: 'com.google.android.gms'
        exclude group: 'com.android.support'
    }**

- Do you have the localization permission granted?

**Yes**

- Android monitor shows any log related to the library when the error is shown?

NO

## Screenshots
![pk](https://user-images.githubusercontent.com/23229626/35042073-e6d2adec-fba8-11e7-8a4e-1b576e3bd812.JPG)

**Comment by ahsen-tekgenisys** [comment]
Tried same locale 'en_PK' and Facing same issue with search suggestions. What should be the solution ? Is there any functionality to change the default locale to Pakistan ?

**Comment by ferranpons** [comment]
Hi @ahmedjamshed @ahsen-tekgenisys !
I'm sorry, unfortunately Pakistan is not available as a Locale in Leku right now. I'll add the support for Pakistan in the next release.

Thanks for reporting it

**Comment by ahmedjamshed** [comment]
![capture](https://user-images.githubusercontent.com/23229626/35153274-ab24aa20-fd47-11e7-9450-7583cc196e98.JPG)

@ferranpons I encountered this error when I tried to update to version 4.0.0. 
 I resolved this error by using this line in build.gradle 

**compile 'pl.charmas.android:android-reactive-location2:2.1@aar'**

BTW Thanks for implementing Locale and it's working fine now.

**Comment by ferranpons** [comment]
@ahmedjamshed I'm glad Pakistan locale is working now. The error about reactive location library not found is weird because is bundled with Leku so you don't need to include the compile/implementation line. Try to make a clean/rebuild it should work without it. :S

I'm closing this issue because the original error is solved. Thanks for your submission.

If you're still experiencing that issue I'll open a new issue.
