### ISSUE TITLE
Unable to integrate in my code.

### ISSUE THREAD

**Issue by talhahafeez88** [SchibstedSpain/Leku#144]
Hi,
I am unable to get rid of this exception at time of library integration in my code. Any help.

Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed with multiple errors, see logs

**Comment by ferranpons** [comment]
Hi @talhahafeez88 !

Please could you provide more info about the issue? Part of the stacktrace withtout sensible data would be useful.

Analyzing the message looks like it's something related to your manifest. Or maybe you are using a different version of the Support library.

**Comment by talhahafeez88** [comment]
Support library is version is v7:27.0.2

It is the issue coming at time library sync. Removing your library from the list, everything starts to sync and works fine. 
Project is quite old while its min sdk version is 16 and compile sdk version is 27. kotlin version is 1.1.51

list of other libraries are
{
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.android.support:multidex:1.0.2'
    //noinspection GradleCompatible
    compile 'com.android.support:appcompat-v7:27.0.2'
    compile 'com.jakewharton:butterknife:8.8.1'
    annotationProcessor 'com.jakewharton:butterknife-compiler:8.8.1'
    compile 'com.bigkoo:svprogresshud:1.0.6'
    compile 'com.squareup.retrofit2:retrofit:2.3.0'
    compile 'com.squareup.retrofit2:converter-gson:2.3.0'
    compile 'com.squareup.okhttp3:logging-interceptor:3.9.0'
    compile 'com.android.support:support-v4:27.0.2'
    compile 'com.github.JakeWharton:ViewPagerIndicator:2.4.1'
    compile 'com.android.support:recyclerview-v7:27.0.2'
    compile 'com.android.support:design:27.0.2'
    compile 'com.github.rahatarmanahmed:circularprogressview:2.5.0'
    compile 'com.squareup.picasso:picasso:2.5.2'
    compile 'com.soundcloud.android:android-crop:1.0.1@aar'
    compile 'com.facebook.android:facebook-android-sdk:4.29.0'
    compile 'com.google.android.gms:play-services-auth:11.8.0'
    compile 'com.google.android.gms:play-services-maps:11.8.0'
    compile 'com.google.android.gms:play-services-places:11.8.0'
    compile 'com.twitter.sdk.android:twitter-core:3.1.0'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    compile 'com.google.firebase:firebase-messaging:11.8.0'
    compile 'com.google.firebase:firebase-core:11.8.0'
    compile 'com.github.satyan:sugar:1.5'
    compile 'com.seatgeek:placesautocomplete:0.3-SNAPSHOT'
    compile 'com.shehabic.droppy:Droppy:0.6.0@aar'
    compile 'com.splitwise:tokenautocomplete:2.0.8@aar'
    compile 'me.shaohui.advancedluban:library:1.3.5'
    compile 'org.ocpsoft.prettytime:prettytime:4.0.1.Final'
	    testCompile 'junit:junit:4.12'
    compile('com.crashlytics.sdk.android:crashlytics:2.7.0@aar') {
        transitive = true
    }
    compile "org.jetbrains.kotlin:kotlin-stdlib-jre7:$kotlin_version"
}
apply plugin: 'com.google.gms.google-services'
apply plugin: 'kotlin-android-extensions'

**Comment by talhahafeez88** [comment]
The issue was due to allowbakup=false in my manifest. Now it is throwing Error:com.android.builder.dexing.DexArchiveBuilderException: Error while dexing com/schibstedspain/leku/LocationPicker.class.

any help!

**Comment by talhahafeez88** [comment]
finally, it has worked for me

https://discuss.kotlinlang.org/t/problem-with-kotlin-compiler-embeddable-1-1-60/5583/2

**Comment by ferranpons** [comment]
@talhahafeez88 good to know that you found a solution. 😉

**Comment by talhahafeez88** [comment]
Error:Execution failed for task ':app:transformClassesWithDesugarForDebug'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: com.android.ide.common.process.ProcessException: Error while executing java process with main class com.google.devtools.build.android.desugar.Desugar with arguments {@...\app\build\intermediates\tmp\desugar_args8541108230401534793}

Unable to get rid of this error, on another project. Any help!

**Comment by talhahafeez88** [comment]
Error:java.lang.ClassNotFoundException: Class io.reactivex.ObservableOnSubscribe not found
Error:Execution failed for task ':app:transformClassesWithDesugarForDebug'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: com.android.ide.common.process.ProcessException: Error while executing java process with main class com.google.devtools.build.android.desugar.Desugar with arguments {@C:\dev_area\BumpIn\Code\brandin\app\build\intermediates\tmp\desugar_args8870165836601642963}

this is another exception coming.

**Comment by talhahafeez88** [comment]
Need to explicitly add these libraries

    implementation "io.reactivex:rxandroid:1.2.1"
    implementation 'io.reactivex.rxjava2:rxjava:2.1.7'
    implementation 'io.reactivex.rxjava2:rxandroid:2.0.1'
    implementation 'nl.littlerobots.rxlint:rxlint:1.6'

**Comment by ferranpons** [comment]
@talhahafeez88 please could you open a new issue? The issue is weird, those libraries are provided with Leku. Please check if you are using the new D8 dexer and try to disable it. Or clean/rebuild the project and sync again.
