### ISSUE TITLE
Gradle wont build

### ISSUE THREAD

**Issue by Tchowpy** [SchibstedSpain/Leku#150]
## Description
/Users/Yougourta/.gradle/caches/transforms-1/files-1.1/leku-4.0.0.aar/4bda711acace361e9e11078cafd09d20/res/layout/leku_activity_location_picker.xml
Error:error: attribute 'com.example.yougourta.leku_test:fabSize' not found.
Error:error: attribute 'com.example.yougourta.leku_test:rippleColor' not found.
Error:error: attribute 'com.example.yougourta.leku_test:fabSize' not found.
Error:error: attribute 'com.example.yougourta.leku_test:rippleColor' not found.
Error:error: attribute 'com.example.yougourta.leku_test:fabSize' not found.
Error:error: attribute 'com.example.yougourta.leku_test:rippleColor' not found.
Error:attribute 'com.example.yougourta.leku_test:fabSize' not found.
Error:attribute 'com.example.yougourta.leku_test:rippleColor' not found.
Error:attribute 'com.example.yougourta.leku_test:fabSize' not found.
Error:attribute 'com.example.yougourta.leku_test:rippleColor' not found.
Error:attribute 'com.example.yougourta.leku_test:fabSize' not found.
Error:attribute 'com.example.yougourta.leku_test:rippleColor' not found.
/Users/Yougourta/.gradle/caches/transforms-1/files-1.1/leku-4.0.0.aar/4bda711acace361e9e11078cafd09d20/res/layout-normal-v4/leku_activity_location_picker.xml
Error:error: attribute 'com.example.yougourta.leku_test:fabSize' not found.
Error:error: attribute 'com.example.yougourta.leku_test:rippleColor' not found.
Error:error: attribute 'com.example.yougourta.leku_test:fabSize' not found.
Error:error: attribute 'com.example.yougourta.leku_test:rippleColor' not found.
Error:error: attribute 'com.example.yougourta.leku_test:fabSize' not found.
Error:error: attribute 'com.example.yougourta.leku_test:rippleColor' not found.
Error:attribute 'com.example.yougourta.leku_test:fabSize' not found.
Error:attribute 'com.example.yougourta.leku_test:rippleColor' not found.
Error:attribute 'com.example.yougourta.leku_test:fabSize' not found.
Error:attribute 'com.example.yougourta.leku_test:rippleColor' not found.
Error:attribute 'com.example.yougourta.leku_test:fabSize' not found.
Error:attribute 'com.example.yougourta.leku_test:rippleColor' not found.
/Users/Yougourta/.gradle/caches/transforms-1/files-1.1/leku-4.0.0.aar/4bda711acace361e9e11078cafd09d20/res/layout-xlarge-v4/leku_activity_location_picker.xml
Error:error: attribute 'com.example.yougourta.leku_test:fabSize' not found.
Error:error: attribute 'com.example.yougourta.leku_test:rippleColor' not found.
Error:error: attribute 'com.example.yougourta.leku_test:fabSize' not found.
Error:error: attribute 'com.example.yougourta.leku_test:rippleColor' not found.
Error:error: attribute 'com.example.yougourta.leku_test:fabSize' not found.
Error:error: attribute 'com.example.yougourta.leku_test:rippleColor' not found.
Error:attribute 'com.example.yougourta.leku_test:fabSize' not found.
Error:attribute 'com.example.yougourta.leku_test:rippleColor' not found.
Error:attribute 'com.example.yougourta.leku_test:fabSize' not found.
Error:attribute 'com.example.yougourta.leku_test:rippleColor' not found.
Error:attribute 'com.example.yougourta.leku_test:fabSize' not found.
Error:attribute 'com.example.yougourta.leku_test:rippleColor' not found.
/Users/Yougourta/.gradle/caches/transforms-1/files-1.1/leku-4.0.0.aar/4bda711acace361e9e11078cafd09d20/res/layout-normal-v21/leku_activity_location_picker.xml
Error:error: attribute 'com.example.yougourta.leku_test:fabSize' not found.
Error:error: attribute 'com.example.yougourta.leku_test:rippleColor' not found.
Error:attribute 'com.example.yougourta.leku_test:fabSize' not found.
Error:attribute 'com.example.yougourta.leku_test:rippleColor' not found.
Error:java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
Error:java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
Error:com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
Error:Execution failed for task ':app:processDebugResources'.
> Failed to execute aapt

**Comment by ferranpons** [comment]
@Tchowpy please could you send me more details?

* targetSdkVersion
* Support library version
* Play services version
...

Thanks!

**Comment by Tchowpy** [comment]
@ferranpons  here are 02 screenshots about the details you asked for

PS : adding leku as a module doesn't show an error.

<img width="1180" alt="screen shot 2018-01-29 at 3 33 43 pm" src="https://user-images.githubusercontent.com/19309698/35515664-107e0c30-050a-11e8-8a7c-5c67ef582c15.png">
<img width="762" alt="screen shot 2018-01-29 at 3 33 58 pm" src="https://user-images.githubusercontent.com/19309698/35515666-10b27c18-050a-11e8-9727-177bbd8e42a4.png">

**Comment by ferranpons** [comment]
@Tchowpy you are using a different version of support library than the one bundled with the library please use this instead of the implementation line:

```
implementation ('com.schibstedspain.android:leku:4.0.0') {
    exclude group: 'com.google.android.gms'
    exclude group: 'com.android.support'
}
```

**Comment by Tchowpy** [comment]
@ferranpons the problem still exists

**Comment by ferranpons** [comment]
@Tchowpy the error is related to the fact that is not finding attributes that comes with the support library. If you have more modules in your project please be sure to use the same support library version. That could lead to this kind of errors.

**Comment by ferranpons** [comment]
@Tchowpy do you have any news about this? Did you solve the problem?

**Comment by Tchowpy** [comment]
@ferranpons , after adding every piece of dependency within the support library, I now get this message. 

<img width="622" alt="screen shot 2018-02-02 at 10 43 00 am" src="https://user-images.githubusercontent.com/19309698/35726679-fcec912e-0805-11e8-831d-092abec82e86.png">
<img width="1142" alt="screen shot 2018-02-02 at 10 42 51 am" src="https://user-images.githubusercontent.com/19309698/35726680-fd58f38c-0805-11e8-9ae3-0f10612404f9.png">

**Comment by ferranpons** [comment]
@Tchowpy are you using the new D8 dexer?

Because this looks like an error with the D8, it's not working very well. Please try to add to your build file `gradle.properties` this line:

`android.enableD8=false`

**Comment by ferranpons** [comment]
@Tchowpy is it working now?
