### ISSUE TITLE
upgrade Google Play Services to 9.4.0

### ISSUE THREAD

**Issue by alexodus** [SchibstedSpain/Leku#16]
Google Play Services 8.4.0 is outdated (dicembre 2015)

**Comment by ferranpons** [comment]
Hi @alexodus! We will upgrade to the latest Google Play Services anytime soon. So please, be patient. I'll communicate you when it's done.

**Comment by ferranpons** [comment]
Hi again @alexodus! A new version of the library is now available. It uses Google Play Services 9.4.0 and the Support Library 24.1.1. Hope it's what you expected. 😉 

Regards.

![happy dance](http://i.giphy.com/10UeedrT5MIfPG.gif)

Solved with the PR #17

**Comment by ferranpons** [comment]
#17

**Comment by alexodus** [comment]
Thank you very much!!! 👍
