### ISSUE TITLE
dynamically ask for location permission if it was denied previously

### ISSUE THREAD

**Issue by evgenyh** [SchibstedSpain/Leku#164]
Currently if I deny location permission request when opening maps view, and then click on location icon (circle with dot) it simply does nothing and not trying to ask for location permission again.
Expected behavior is accordingly to official google maps app is to reask for permission every time user clicks on location icon.

**Comment by ferranpons** [comment]
Hi @evgenyh !

Thanks for reporting it! I'll take a look and include it for the next releases!

**Comment by ferranpons** [comment]
Hi @evgenyh ! 

It will be solved in the version 5.0.0 😉

**Comment by evgenyh** [comment]
Hi @ferranpons , when 5.0.0 planned to release ?
thanks

**Comment by ferranpons** [comment]
@evgenyh this week. Hopefully if all goes as expected it will be between today and tomorrow. 😉

**Comment by ferranpons** [comment]
New release version 5.0.0 now available for download. I'm closing this issue because it's solved with the latest version. If it fails again please reopen the issue. Many thanks for reporting it and for using this library!

**Comment by evgenyh** [comment]
thank you!
