### ISSUE TITLE
Add SearchZone for VietNam

### ISSUE THREAD

**Issue by hangocanh2303** [SchibstedSpain/Leku#172]

**Comment by ferranpons** [comment]
Hi @hangocanh2303!

Thanks for your submission! I've added the Search zone on the PR #174

**Comment by hangocanh2303** [comment]
@ferranpons thank you very much.

**Comment by hangocanh2303** [comment]
@ferrangrau  this working with CountryLocaleRect.java file?

**Comment by ferrangrau** [comment]
@ferranpons no @ferrangrau jejeje

**Comment by ferranpons** [comment]
New release version 5.0.0 now available for download. I'm closing this issue because it's solved with the latest version. If it fails again please reopen the issue. Many thanks for reporting it and for using this library!
