### ISSUE TITLE
 java.lang.NoSuchMethodError: No static method getGeoDataClient() v 5.0.0

### ISSUE THREAD

**Issue by Midhilaj** [SchibstedSpain/Leku#200]
` java.lang.NoSuchMethodError: No static method getGeoDataClient(Landroid/app/Activity;Lcom/google/android/gms/location/places/PlacesOptions;)Lcom/google/android/gms/location/places/GeoDataClient; in class Lcom/google/android/gms/location/places/Places; or its super classes (declaration of 'com.google.android.gms.location.places.Places' appears in /data/app/com.valyangadi.androidapp-2/base.apk:classes2.dex)`

i enabled api and added api key but it is showing above error on start

                      ```
          startActivityForResult( new LocationPickerActivity.Builder()
                                        .withLocation(41.4036299, 2.1743558)
                                        .withGeolocApiKey("key=myapikey")
                                        .withSearchZone("es_ES")
                                        .shouldReturnOkOnBackPressed()
                                        .withStreetHidden()
                                        .withCityHidden()
                                        .withZipCodeHidden()
                                        .withSatelliteViewHidden()
                                        .build(getApplicationContext()), 654);

```

**Comment by gvsharma** [comment]
The method in LocationPickerActivity needs to be modified as per new googleplacesAPI docs. The getGeoDataClient object needs to be created with following params.

`getGeoDataClient(this)`

@ferranpons 
i have create PR, please accept it

Thank you

**Comment by ferranpons** [comment]
@gvsharma You're right, we are using a deprecated method. I've accepted your PR.

Many thanks for your contribution.

**Comment by gvsharma** [comment]
Welcome.. happy to join here as contributor

**Comment by Midhilaj** [comment]
Failed to resolve: com.schibstedspain.android:leku:5.1.0

**Comment by Midhilaj** [comment]
what is the solution?

**Comment by gvsharma** [comment]
try 5.1.1

**Comment by Midhilaj** [comment]
Failed to resolve: com.schibstedspain.android:leku:5.1.1

**Comment by ferranpons** [comment]
@Midhilaj @gvsharma version 5.1.1 will be published soon. Please wait a bit.

![please wait](https://media.giphy.com/media/3o6Ztl5XZaXwjl6WEE/giphy.gif)

**Comment by Midhilaj** [comment]
we are waiting

**Comment by ferranpons** [comment]
@Midhilaj @gvsharma finally it's here. New version 5.1.1 is ready for download. If you still have issues please re-open this issue or create a new one.

Many thanks for your contribution!

**Comment by Midhilaj** [comment]
Failed to resolve: com.schibstedspain.android:leku:5.1.1

**Comment by Midhilaj** [comment]
https://github.com/SchibstedSpain/Leku/issues/206
