### ISSUE TITLE
Failed to resolve: com.schibstedspain.android:leku:5.1.1

### ISSUE THREAD

**Issue by aliondos** [SchibstedSpain/Leku#204]
I've been having an issue updating Leku since the first build of 5.1.0, any help would be appreciated.

**Comment by Midhilaj** [comment]
it is available @ https://bintray.com/schibstedspain/maven/leku/5.1.1
[download](https://dl.bintray.com/schibstedspain/maven/)

**Comment by ferranpons** [comment]
@aliondos It's solved with the latest version released (v5.1.3). I'm closing this issue.
