### ISSUE TITLE
Search button

### ISSUE THREAD

**Issue by Jucedik** [SchibstedSpain/Leku#22]
Please add custom button for apply text search.
Some blonde girls not known about default search button on keyboard.

**Comment by ferranpons** [comment]
@Jucedik definitely we will check this out. Please be patient because we are on holidays, so in some days you will have an answer to this.

**Comment by ferranpons** [comment]
@Jucedik this functionality it's on its way. Hope it is what you're looking for. 😉

**Comment by Jucedik** [comment]
Thanks man  :+1:

**Comment by ferranpons** [comment]
Solved with PR #27

**Comment by ferranpons** [comment]
@Jucedik version 2.1.0 is now available for download. Enjoy!

![happy dance](http://i.giphy.com/10u1etNHGbmcwg.gif)

**Comment by Jucedik** [comment]
@ferranpons thanks friend! :)
