### ISSUE TITLE
Is there a way to disable the filter by Search Zone 

### ISSUE THREAD

**Issue by jayfrostjay** [SchibstedSpain/Leku#226]
## Description
Is there a way to disabled the filter by Search Zone , removed the Search zone and allow to search location to all zones? If i remove the withSearchZone("es_ES") paramater it will still restrict the filters to it's Locale.getDefault. Thanks!

**Comment by jayfrostjay** [comment]
Hi, Fixed...

Did removed the if statement in function retrieveDebouncedLocationFromDefaultZone

**Comment by iago-silva** [comment]
@jayfrostjay can u explain me better? I've same problem, but I can not fix it :/

**Comment by jayfrostjay** [comment]
@iago-silva Hi, first i did imported the leku as a module instead of adding it on the gradle file as dependency,
  
![image](https://user-images.githubusercontent.com/25005381/53456142-24cdfd00-3a68-11e9-81a2-44ce2bc30bfc.png)
  
After that i modified the function <b>retrieveDebouncedLocationFromDefaultZone </b> in <b>LocationPickerActivity.kt</b> to this

![image](https://user-images.githubusercontent.com/25005381/53456193-6199f400-3a68-11e9-9f4e-47c33f30dc3d.png)

This will remove the zones filter in the search results, zones filter are all defined inside the library i just did remove that feature. 

Hope that helps

**Comment by iago-silva** [comment]
@jayfrostjay Grateful!!

Should have its own methods to remove that filter or add your own bottom-left and top-right coordinates

**Comment by ferranpons** [comment]
Hi @iago-silva @jayfrostjay 

I'll create an option to disable the search zone filter ASAP.

![acknowledge](https://media.giphy.com/media/3ohs4jj2XVeZ8Z2T8Q/giphy.gif)

**Comment by ferranpons** [comment]
PR #230 will solve this. 😉

**Comment by ferranpons** [comment]
Hi @iago-silva @jayfrostjay

New version 6.1.0 is available for download and includes the option to not search with zone. Now, by default, you search without zone restriction and search zone is an optional value.

Hope this solves your problem.

![done](https://media.giphy.com/media/9Jcw5pUQlgQLe5NonJ/giphy.gif)
