### ISSUE TITLE
Add SearchZone for Brazil

### ISSUE THREAD

**Issue by iago-silva** [SchibstedSpain/Leku#227]

**Comment by ferranpons** [comment]
Hi @iago-silva !

I've added Brazil to the search zone. PR #228 

Many thanks for your submission!

**Comment by ferranpons** [comment]
@iago-silva new version 6.1.0 is available and includes Brazil as a search zone.
I'm closing the issue. If you find something else don't hesitate and create a new issue.

Many thanks

**Comment by iago-silva** [comment]
Thank you 😬
