### ISSUE TITLE
If the phone has some issue with Geocoder, the user gets stuck

### ISSUE THREAD

**Issue by rocboronat** [SchibstedSpain/Leku#23]
Don't know why, my phone got an issue with Geocoder and never received the data from Google until I rebooted it. For sure it's not a common issue but... it happens 😢 

What about using the non-Android API to get that data when it happens? https://developers.google.com/maps/documentation/geocoding/intro

**Comment by ferranpons** [comment]
@rocboronat that looks like a weird behavior. Anyway, you're right we need a "fallback" if geocoder is not working well. We will look into that soon. Thanks for your suggestion. :wink:

**Comment by rocboronat** [comment]
No prob! If we notice the issue again, I'll share it with you. Hopefully, it will never happen again, so we can focus on cold beer 🍻 🍺

**Comment by ferranpons** [comment]
@rocboronat I close this issue. If you reproduce this again in the future please reopen the issue. 😉

**Comment by rocboronat** [comment]
Time to focus on cold beer, then! :·)

**Comment by ferranpons** [comment]
Sure!
