### ISSUE TITLE
Wrong address returned

### ISSUE THREAD

**Issue by Lars-** [SchibstedSpain/Leku#231]
**Describe the bug**
When you click on a location that doesn't have an address, it returns the address of the last location that had an address.

**To Reproduce**
Click on a random spot in the sea, the latitude and longitude are returned correct, but the address will be the address on your location.

**Expected behavior**
Return null (or "Invalid Address")

**Info Required**
- Which version of the library do you actually use?
6.1.0

- Do you have the localization permission granted?
Yes

- Are you sending parameters to the activity through the bundle?
Uhm, I don't know.

- Android monitor shows any log related to the library when the error is shown?
It's not an error

- Any other thing that could help me to reproduce the error?
It's a simple problem.

**Smartphone:**
 - Device: Emulator Nexus 5X

**Comment by ferranpons** [comment]
Hi @Lars- 

I'll check it ASAP. Many thanks for reporting it.

**Comment by ferranpons** [comment]
@Lars- new release version 6.1.1 is now available for download. It solves this issue.

Many thanks for reporting it. 🍷 😉

**Comment by Lars-** [comment]
Awesome, thanks man!
