### ISSUE TITLE
Library changes my color scheme

### ISSUE THREAD

**Issue by DennyWeinberg** [SchibstedSpain/Leku#243]
When adding the library to my project, the colors of my buttons and fab's change without any OTHER changes.

**To Reproduce**
Add this to your project:
```
implementation ('com.schibstedspain.android:leku:6.2.0') {
    exclude group: 'com.google.auto.value'
}
```

**Expected behavior**
Colors should not change

**Info Required**
The color is changed for all activities, not only the place picker one.

**Screenshots**
Before:
![before](https://i.imgur.com/d8bPhJd.jpg)

After:
![after](https://i.imgur.com/kOoyTMd.jpg)

**Smartphone:**
 - Device: Samsung Galaxy S9

**Additional context**
My styles.xml:
```
<style name="LevionAppTheme.Dark" parent="Theme.MaterialComponents.NoActionBar">
    <!--item name="android:windowFullscreen">true</item-->
    <item name="windowActionModeOverlay">true</item>
    <item name="android:windowBackground">@color/background.dark</item>
    <item name="colorPrimary">@color/colorPrimary.dark</item>
    <item name="colorPrimaryDark">@color/colorPrimaryDark.dark</item>
    <item name="android:textColorPrimary">@color/textColorPrimary.dark</item>
    <item name="android:textColorSecondary">@color/textColorSecondary.dark</item>
    <item name="android:textColorPrimaryInverse">@color/textColorPrimary</item>
    <item name="android:textColorSecondaryInverse">@color/textColorSecondary</item>
[...]
```

**Manifest:**
```
<application
    android:name=".MyApplication"
    android:allowBackup="true"
    android:icon="@mipmap/ic_launcher"
    android:label="@string/my_app_name"
    android:theme="@style/LevionAppTheme"
    tools:replace="android:theme,android:label"
    android:largeHeap="true"
    >
```

```
<activity
    android:name="com.schibstedspain.leku.LocationPickerActivity"
    android:configChanges="screenSize|orientation|keyboardHidden">
    <meta-data
        android:name="android.support.PARENT_ACTIVITY"
        android:value=".MainAppActivity" />
</activity>
```

**Comment by ferranpons** [comment]
Hi @DennyWeinberg 

This should not happen since the library use the resource prefix to avoid this kind of issues.

Looking at the code you shared the only thing that could avoid this to happen is the line in the manifest:
`tools:replace="android:theme,android:label"`
You are telling to the manifest merger to override the theme in case it's duplicated. Try to do the same on the activity you are experiencing this issue by adding the same "android:theme".

However, I'll try to reproduce the issue.

**Comment by DennyWeinberg** [comment]
Hello,

I need that because of that dumb net.rdrei.android.dirchooser library. (https://github.com/passy/Android-DirectoryChooser/issues/85)

I have to find a solution. I already know that it's not your library who causes the problem, because I updated some other libraries and now I have the same issue in my app without using your lib.

**Comment by ferranpons** [comment]
@DennyWeinberg 

Since is not related to this library I have not much to say. I could help you but It would be helpful to have an example that reproduces the problem. Please could you provide a github repository reproducing the error? And I'll try to help. Otherwise, I'll close this issue.

**Comment by DennyWeinberg** [comment]
Ok. Thank you! I will contact you when I am able to reproduce it in a small project.
