### ISSUE TITLE
The search box text is not vertically centered

### ISSUE THREAD

**Issue by rocboronat** [SchibstedSpain/Leku#26]
It happens on a Samsung Galaxy J5. I'll fix it for sure before ending the week if no one else fixed it before :·) 

![screenshot_2016-08-29-13-05-34](https://cloud.githubusercontent.com/assets/456499/18049579/73fadd88-6de9-11e6-82ed-e738f9987bb5.png)

**Comment by ferranpons** [comment]
Solved with PR #27

**Comment by rocboronat** [comment]
Thanks @ferranpons !

**Comment by ferranpons** [comment]
@rocboronat You're welcome! 😉 

![youwelcome](http://i.giphy.com/fm5JqspHFgIXm.gif)
