### ISSUE TITLE
Reduce method counts

### ISSUE THREAD

**Issue by k0shk0sh** [SchibstedSpain/Leku#29]
Hello There, Could you please make a separate builds for the library? the soon i add it to my project, i got   

> Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexIndexOverflowException: method ID not in [0, 0xffff]: 65536  

by analysing the library in [Methods Count](http://www.methodscount.com/?lib=com.schibstedspain.android%3Aleku%3A2.1.0) 
it says that it has **38540 methods** the library itself has **433** and 16 dependency, if you could make two separate builds a one with Rx, lambda & one without them to reduce the method count that had be great. 

Thanks

**Comment by ferranpons** [comment]
Hello @k0shk0sh 

I am concerned with the problem this may cause to you. But, If you analyze the total count in depth, you will find that the most of it are the support library. The RxJava has 5600 methods approximately. It's still large but not the main reason for the large method count. 

Sadly Google libraries are mandatory for this library, but If you still think that RxJava is a problem for you, I encourage you to fork the library and send a PR that removes RxJava.

Alternatively, if you are not using Proguard yet (I hope you're actually doing), please use it so it will decrease your method count on a release version dramatically.


Thanks for your suggestion, and sorry for the problems that it may cause to you.

**Comment by k0shk0sh** [comment]
Thank @ferranpons for your response, i'll be definitely be using progaurd but since i'm actually still in earlier development i can't do it right now, and even if i did, i'll have to use MultiDex which tbh i don't want to use it, i'll definitely create PR when i get free time,  currently, i cloned the project removed retrolambda and kept RxJava but yet i'm getting the same result, i guess we have to take out RxJava as well. meantime i chose not to use the library even tho it suits exactly what i wanna achieve due to the short time i have to deliver current app. 
Again, Thank you very much for you response.

**Comment by CristianGM** [comment]
Anyway considering RxJava it's about 5k methods, maybe the real problem is simply Play Services, or the Support Lib, and they are both required.

Only if it is by just this 5k methods or less that you are over the 65k, it will matter.

**Comment by ferranpons** [comment]
But If it's a matter of 5k of methods... Proguard would solve the issue. And it's not so difficult to add if the app is in an early state...

**Comment by k0shk0sh** [comment]
@CristianGM  definitely agree. 
@ferranpons it isn't hard true, but considering the build time that gradle will take for every run to test something is actually a problem. 
i'll try to investigate more  on the libraries i currently use, even tho, they are the same ones i use for almost every project and never hit that problem. i'll update here once i analyzed the libraries.

**Comment by ferranpons** [comment]
@k0shk0sh I understand... it's difficult to manage so many dependencies, every time you add one it increases a lot the build time. Let me know when you analyze these libraries. 😉 

Thanks!

**Comment by ferranpons** [comment]
@k0shk0sh any news about this? Can we close it?

**Comment by k0shk0sh** [comment]
@ferranpons I'm really sorry, i really couldn't find the time to go through it as by that time i just used google Places API and that was it. if i have any future projects that requires such functionality i'll look into it again.
