### ISSUE TITLE
OnActivity result always returns RESULT_OK.

### ISSUE THREAD

**Issue by borjaruiz** [SchibstedSpain/Leku#33]
Hi, thanks for this library, I'm having a problem:

When I press the back arrow or the phisical back button, onActivity result is detecting RESULT_OK, why? 

Thanks in advance

**Comment by ferranpons** [comment]
Hi @borjaruiz,

It's possible that it returns "RESULT_OK" If you have changed the location on the map, I assume that you want to change the location and when you click on the back button it sends the "RESULT_OK". 
This was a decision on our product. If you think it's a bad behavior we can discuss it and maybe change it.

:)

**Comment by borjaruiz** [comment]
I didn't changed the location, maybe it's returning OK because it's autocentering in my current location?
I just open the Activity, and it detects my current location, then "I call" onBackPressed() and it's returning OK. 

I think back arrow toolbar should return cancel because you have the "ok/check" floating button that has that function. If not, user never cancel the action. Is it? 

Thanks for your quick reply.

**Comment by ferranpons** [comment]
You're right, it's a possible behavior. Also, you could cancel the action if you provided a location when you start the activity and when coming back this location have not changed. But obviously, it's not the desired behavior from your point of view.

I'll modify it to allow both options.

**Comment by ferranpons** [comment]
@borjaruiz It will be solved in the next release. PR #35  😉

**Comment by borjaruiz** [comment]
Perfect! Thanks!
