### ISSUE TITLE
Can't add dependency  in my  project.It shows Error

### ISSUE THREAD

**Issue by pankajjangid** [SchibstedSpain/Leku#4]
![capture 1](https://cloud.githubusercontent.com/assets/16424754/17284949/e64f8e38-57dc-11e6-9adb-5d12fa57ab02.PNG)

**Comment by ferranpons** [comment]
@pankajjangid I'm sorry. I have to apologise because it's still not available on maven/jcenter. I hope it will be available between today and tomorrow. I'll send you an update when it becomes available for download.

![sorry](http://i.giphy.com/rvDtLCABDMaqY.gif)

**Comment by pankajjangid** [comment]
Please ,do it fast ,it is look like very useful & great .

Thanks

**Comment by ferranpons** [comment]
@pankajjangid You can use the jitpack version until it gets published officially.

repositories {
    maven {
        url "https://jitpack.io"
    }
}

dependencies {
    compile 'com.github.SchibstedSpain:Leku:0e6cef1b0d'
}

**Comment by ferranpons** [comment]
@pankajjangid It's now available with the correct package on jcenter so you don't need anymore the jitpack version. Sorry for the inconvenience. Hope this library is useful for you. Enjoy!

> compile 'com.schibstedspain.android:leku:1.0.0'

If you have more problems don't hesitate to create more "issues". 😉 

Regards.



Solved with the PR #10
