### ISSUE TITLE
Can't customize colors...

### ISSUE THREAD

**Issue by grestuccia1** [SchibstedSpain/Leku#42]
![can_change_color](https://cloud.githubusercontent.com/assets/5777472/19446114/a89f5528-946d-11e6-8b51-52d5850fbd21.png)

i've seen the resource "ic_gps_lime.png", and i can't change color.

style.xml

    <style name="Base.Theme.F4M" parent="Theme.AppCompat.Light.NoActionBar">
        <item name="colorPrimary">#3F51B5</item>
        <item name="colorPrimaryDark">#303F9F</item>
        <item name="colorAccent">#498dfb</item>
   </style>

manifest.xml

 <activity
            android:name="com.schibstedspain.leku.LocationPickerActivity"
            android:label="@string/title_activity_location_picker"
            android:theme="@style/Base.Theme.F4M"
            android:windowSoftInputMode="adjustPan"
            android:parentActivityName=".view.activity.NewFavorActivity">
            <intent-filter>
                <action android:name="android.intent.action.SEARCH" />
            </intent-filter>
            <meta-data android:name="android.app.searchable"
                android:resource="@xml/searchable" />
            <meta-data
                android:name="android.support.PARENT_ACTIVITY"
                android:value=".view.activity.NewFavorActivity" />
        </activity>

**Comment by ferranpons** [comment]
Hi @grestuccia1!

I'll take a look and I'll answer you back.

Ooops... 😅 

![giphy 41](https://cloud.githubusercontent.com/assets/1225463/19510868/3485b5b4-95e5-11e6-8150-c8118299e372.gif)

**Comment by ferranpons** [comment]
@grestuccia1 a Fix is on its way. Please checkout PR #44 

![giphy 43](https://cloud.githubusercontent.com/assets/1225463/19641472/209387d4-99e1-11e6-9f7e-1e5db9154c9d.gif)

**Comment by ferranpons** [comment]
@grestuccia1 version 2.3.0 is now available for download! Hope it solves your problem. 

![giphy 44](https://cloud.githubusercontent.com/assets/1225463/19682202/d0575a76-9aac-11e6-9b56-4ffcf44b06e6.gif)
