### ISSUE TITLE
Support Satalite Map view

### ISSUE THREAD

**Issue by galadril** [SchibstedSpain/Leku#59]
New feature request, please als add support Satalite view.

![image](https://cloud.githubusercontent.com/assets/14561640/22820424/043d043e-ef77-11e6-8691-d98375bf8096.png)

**Comment by ferranpons** [comment]
Hi @galadril 

How do you want it? Do you want it to be set through the bundle? or a button to change the type of map being displayed?


Many thanks!

**Comment by galadril** [comment]
I think that a button to switch views is the cleanest solution. right?

**Comment by ferranpons** [comment]
👍 

I'll work into it as soon as I can. Thanks for your suggestion.

**Comment by galadril** [comment]
Thanks, looking forward to it..
I've implemented this location picker in my Home Automation app (Domoticz)

**Comment by galadril** [comment]
Any idea on planning?

**Comment by ferranpons** [comment]
@galadril I'm working on it. You will got it within this week. 😉

**Comment by ferranpons** [comment]
Hi @galadril!

A new version is available (is being generated right now) with the satellite button! Hope it's what you expected.

Enjoy!

Version 3.1.0 😉

**Comment by galadril** [comment]
Thanks bro!
I'll check it right away :)

**Comment by galadril** [comment]
Works amazing, thanks a lot!
🥇

**Comment by ferranpons** [comment]
You're welcome! Glad you like it. 😉 

![happy](https://media.giphy.com/media/rjkJD1v80CjYs/giphy.gif)
