### ISSUE TITLE
LocationPickerActivity.SEARCH_ZONE not working!!!

### ISSUE THREAD

**Issue by ashaantony** [SchibstedSpain/Leku#63]
I want to show the LocationPickerActivity to only display place searches and location results within UAE. I tried to set SEARCH ZONE as mentioned below.

```
Intent placePickerIntent = new Intent(this, LocationPickerActivity.class);
placePickerIntent.putExtra(LocationPickerActivity.SEARCH_ZONE, "ar_AE");
placePickerIntent.putExtra(LocationPickerActivity.BACK_PRESSED_RETURN_OK, true);
startActivityForResult(placePickerIntent, PLACE_PICKER_REQUEST);
```

But is not working. Instead of showing the results within UAE, t is showing the rresults from all around. Please help.

**Comment by ferranpons** [comment]
@ashaantony that's a good point. That was not meant to work on a whole region. It's a good improvement. I'll improve it as soon as I can.

Thanks for your report!

**Comment by sprengerst** [comment]
In our project we tried with de_DE as locale, but we get all around and only some DE Places are working. I'm really confused why it works for some places and for others not?

**Comment by sprengerst** [comment]
Can we do something to improve this?

**Comment by ferranpons** [comment]
@ashaantony @sprengerst to improve this we can add the UAE or whatever region rect coordinates we would like in the CountryLocaleRect.java class for now. In a future release we could parametrize that to inject your desired zone when instantiating the LocationPickerActivity.

I'm going to add the coordinates and create a release. 😉

**Comment by sprengerst** [comment]
Your future release plans do sound great. I would really appreciate to set a custom desired zone to as example include the DACH region or Europe.

**Comment by ferranpons** [comment]
@sprengerst that would require more time to develop. I'll try to do it as soon as possible. For now I could all the locales you are working on but not a whole region. Sorry about that.

**Comment by sprengerst** [comment]
@ferranpons 

Ok great thanks. Can I bother you with adding "DACH" region code? from lower left: 45.875834, 6.235783 to right upper 55.130976, 16.922589 , this would solve our issue. I could also do the Pull Request by myself if you don't have the time.

It could maybe work as Locale.GERMAN (don't mistake with Locale.GERMANY) as german speaking area? Or as "DACH" code as example.

**Comment by ferranpons** [comment]
@sprengerst ok, I've updated the PR #108 with DACH Region. 😉

**Comment by sprengerst** [comment]
Thank you very much =)

**Comment by ferranpons** [comment]
@sprengerst @ashaantony New version 3.4.3 now available with the new locales. Hope it solves your issues.

Thanks for your report! And if you still have problems with these locales please reopen this issue or write a new message. Enjoy!

![](https://media.giphy.com/media/6oB3X3W6MYM3C/giphy.gif)
