### ISSUE TITLE
Search Api

### ISSUE THREAD

**Issue by devineed** [SchibstedSpain/Leku#74]
Hi sir,
firstly, this is a great lib that i need. Because i need for user to pick freely the position on map, and not like google placepicker that only limits to a place (can't move pin position when search).

But the problem is, the search function seems not showing the good results like place picker does.
It has so limited results. Is there any way to improve so the search is like on place picker?

Thanks

**Comment by abeemukthees** [comment]
I'm also facing the same issue

**Comment by ferranpons** [comment]
Hi @devineed 

Are you using the search zone variable when instantiating the intent?

> intent.putExtra(LocationPickerActivity.SEARCH_ZONE, "es_ES"); // this is optional if an specific search location

Because, if you're not using it, all your searches using the search view input are headed for all around the world and could not be as precise as you would like.

**Comment by ferranpons** [comment]
@devineed @abeemukthees have you tried using the search zone?

**Comment by abeemukthees** [comment]
Hi @ferrangrau  Thank you for replying. I haven't tried using the search zone. Let me try it & update you

**Comment by ferranpons** [comment]
@abeemukthees any news about this?

**Comment by ferranpons** [comment]
@abeemukthees I assume that this is working now so I'm closing the issue. If you still experience this issue please reopen it again. Thanks!

**Comment by hangocanh2303** [comment]
@ferranpons you can help me add VietNam search zone? many thanks
