### ISSUE TITLE
The address / location is not found.

### ISSUE THREAD

**Issue by galadril** [SchibstedSpain/Leku#75]
## Description
At some phones, they are not able to select a location. Also the address is not found.
See screenshots, the same address works on different phones.

## Info Required

- Which version of the library do you actually use?
3.1.0

- Do you have the localization permission granted?
yes
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />

- Are you sending parameters to the activity through the bundle?
yes, it works on most of the phones

- Could you describe what are the actions do you make to raise that error?
It doesn't work on a zte axon 7 with android 7.1.

## Screenshots
![ffac5a280ac1291fa8c7f33c2dda58ef](https://cloud.githubusercontent.com/assets/14561640/24942593/450e7618-1f52-11e7-8340-5670e947582b.jpg)
![12e7698199d7bafdb266506056534ca9](https://cloud.githubusercontent.com/assets/14561640/24942594/450f8d46-1f52-11e7-90a0-22edf91ec92c.jpg)

**Comment by galadril** [comment]
Shouldn't it be possible to select a location even when no address is found?
Within my app, im actually only needing the lat/long

**Comment by ferranpons** [comment]
@galadril please could you check if that device has the latest version of play services is installed?

About what you ask, sure! We can implement a fallback that shows the lat/long info without the address. 😉 

Thanks for your report.

**Comment by galadril** [comment]
> We can implement a fallback that shows the lat/long info without the address. 😉  

Thanks 👍

**Comment by galadril** [comment]
I've an issue that some users can't setup geofences because the location picker can't see their address.
It's a huge feature in my app, so quite important.

Any change on the defaulting on lat/long fallback?

**Comment by galadril** [comment]
?

**Comment by ferranpons** [comment]
Hi @galadril !

I'm sorry I had no time to make it. I'll try to do it as soon as I can. Sorry for the inconvenience.

![sorry](https://media.giphy.com/media/3ohA2ZD9EkeK2AyfdK/giphy-tumblr.gif)

**Comment by galadril** [comment]
👍

**Comment by galadril** [comment]
Im really sorry, but I think I need to move away from this location picker. I get lots of complains that they can't select a location on my application (permissions exception and this location not found issue, so they can't select a location without an address)

At this moment Geofences are a core feature on my app and this is not working.

**Comment by ferranpons** [comment]
@galadril sorry to hear that. I understand that is important for your business but you have to understand that I maintain this library on my spare time. So, it's difficult to do it because I have a lot of duties outside my regular work (mainly kids).
I'll try to have it this week, but I cannot assure that will be finished.

Sorry for the inconvenience.

**Comment by galadril** [comment]
Yeah no hard feelings, I know what it is. Domoticz is also spare time project, but that grow larger with daily 10.000+ users. I also can't agree with every issue request that people shoot at me :)

**Comment by galadril** [comment]
Added option to show coordinates when no address is found #87

**Comment by galadril** [comment]
Did you had a chance to look at my pull request?

**Comment by galadril** [comment]
Can you please check and adjust my pull request to you likings/needs?

**Comment by galadril** [comment]
@ferranpons can you make a new release with the changes included??
Then I think we can close this issue request

**Comment by ferranpons** [comment]
@galadril during today you will have a new version. 😉

**Comment by ferranpons** [comment]
@galadril new version 3.3.0 available for right now! Enjoy!
