### ISSUE TITLE
Permission really mandatory?

### ISSUE THREAD

**Issue by galadril** [SchibstedSpain/Leku#76]
**As described on the readme":**

> android.permission.WRITE_EXTERNAL_STORAGE Allows the API to cache map tile data in the device's external storage area.  

**Is this really needed??**

My app only uses the maps for the location picker.. which they setup maybe once.
So can't this location picker also run without caching?

**Comment by galadril** [comment]
lol, the permissions is optional. I've changed the readme

**Comment by ferranpons** [comment]
@galadril Thanks for your contribution.

Will be adressed with the PR #77
