### ISSUE TITLE
ENABLE/DISABLE SATELLITE VIEW NOT WORKING

### ISSUE THREAD

**Issue by devdigitalappteam** [SchibstedSpain/Leku#79]
## Description
intent.putExtra(LocationPickerActivity.ENABLE_SATELLITE_VIEW, false);
parameter not working in bundle passing

## Info Required

- Which version of the library do you actually use?
3.1.0
- Do you have the localization permission granted?
YES
- Are you sending parameters to the activity through the bundle?
YES
- Could you describe what are the actions do you make to raise that error?
LocationPickerActivity.ENABLE_SATELLITE_VIEW not found while library import.
- Android monitor shows any log related to the library when the error is shown?
Editor show the error that variable not found.
- Any other thing that could help me to reproduce the error?

## Screenshots
![image](https://cloud.githubusercontent.com/assets/10204700/25123704/f823d358-2446-11e7-9e9b-c636c56ee044.png)

**Comment by ferranpons** [comment]
@devdigitalappteam I have to apology but the version with this feature is not already published. It's our fault. I'll let you know when is available.

Sorry for the inconvenience.

**Comment by devdigitalappteam** [comment]
Thanks for the quick reply

Also is it possible to make marker (pin) custom it would be helpful for the development end.
If you are working on it then let me know for the so it would great help for me because I am going to integrate this library with my project but one hurdle is that as per application UI map pin should use custom image which design by the designer.

Thanks in  advance.

**Comment by ferranpons** [comment]
@devdigitalappteam solved with the version 3.2.0. BTW I'm going to add a new Issue with the custom poi request.

Thanks for reporting. 😉
