### ISSUE TITLE
Please include timezone...

### ISSUE THREAD

**Issue by AhmadullahSaikat** [SchibstedSpain/Leku#88]
When I select Place it returns Latitude, Longitude, Address, etc
But it is necessary to get timezone by selecting any place from google map..
If you include timezoneId it will be more beneficial for me and other peoples who uses your library...
Please reply...
One more thing,.. how can I get CountryName from FullAddress?
.....................................
Finally I get timezone via latitude and longitude by using google API

**Comment by ferranpons** [comment]
Hi @AhmadullahSaikat ! Sorry for doing it so late but it's implemented now and it will be available on release version 5.0.0 that I hope to be deployed today.

**Comment by ferranpons** [comment]
New release version 5.0.0 now available for download. I'm closing this issue because it's solved with the latest version. If it fails again please reopen the issue. Many thanks for reporting it and for using this library!
