### ISSUE TITLE
How can I show Country name and Country Code?

### ISSUE THREAD

**Issue by AhmadullahSaikat** [SchibstedSpain/Leku#90]
When I print full address it shows countryName and countryCode.
But the format is not valid json format.
So please explain.. how can I get countryName and countryCode.

**Comment by galadril** [comment]
there is an example in MainActivity.cs:

`

Address fullAddress = data.getParcelableExtra(LocationPickerActivity.ADDRESS);
`


Then you can get the Country information via:

```

fullAddress.getCountryCode();
fullAddress.getCountryName();


```

**Comment by AhmadullahSaikat** [comment]
Very good answer......

One more question..
How can I show my current location in Map without setting latitude and longitude..?

In walton device I can show my current location in google map by using following code..
but some devices this code doesn't give me the current location from map.

My Code:

        StrictMode.setThreadPolicy(new StrictMode.ThreadPolicy.Builder().detectAll().penaltyLog().build());
        StrictMode.setVmPolicy(new StrictMode.VmPolicy.Builder().detectAll().penaltyLog().build());
        Intent locationPickerIntent = new LocationPickerActivity.Builder()
                .build(getApplicationContext());
        startActivityForResult(locationPickerIntent, MAP_POIS_BUTTON_REQUEST_CODE);

**Comment by ferranpons** [comment]
@AhmadullahSaikat you need to explicitly set a latitude and longitude or enabled location permission to automatically set your location when intent starts.

**Comment by ferranpons** [comment]
@AhmadullahSaikat I assume that it worked for you. I'm closing the issue. If you are still experiencing this problem please reopen the issue.

Many thanks for using the library. 😉
