### ISSUE TITLE
I didn't see location view API 22 Android LOLIPOP

### ISSUE THREAD

**Issue by jowelAIUB** [SchibstedSpain/Leku#92]
##Not working for API 22 or Less

**Comment by ferranpons** [comment]
@jowelAIUB Please provide more info about your problem.

**Comment by jowelAIUB** [comment]
I added this using gradle . Min sdk is 15 . But i saw locationinfoLayout only for 23 or upper version sdk . Why i can't see that 22 or less sdk . Can you please explain ?

**Comment by ferranpons** [comment]
@jowelAIUB I'm not experiencing this issue with our devices with API below 22. Please could you give me more info about the problem?

* Do you see any log with errors?
* Which device are you using to test?
* Any code or sample reproducing that error would help a lot, if possible.

**Comment by jowelAIUB** [comment]
I have used  this into my project . is need any license  for publish the app  at appStore?

**Comment by ferranpons** [comment]
@jowelAIUB No, you don't need anything to publish you app to the google play store. This library uses the Apache 2.0 License that allows you to use the library in your commercial projects without any problem.

**Comment by ferranpons** [comment]
@jowelAIUB Are you still having issues with the library? Or we can close this issue?

**Comment by ferranpons** [comment]
@jowelAIUB I'm going to close this issue. If you think that it is still not being solved please reopen this issue. Thanks.

**Comment by jowelAIUB** [comment]
it solved. no problem in your project. problem  was on device .  Thanks
