### ISSUE TITLE
Location Search via Text Input

### ISSUE THREAD

**Issue by muellerch93** [SchibstedSpain/Leku#98]
## Description
Hey, amazing lib!
If you search for a location via the Text Input the marker is set correctly to the new location but the "Check button" disappears.  It reappears again if the user clicks onto the map. 
It would be great if you could check this out. Thank You! 

## Info Required

- Which version of the library do you actually use?
3.4.0
- Do you have the localization permission granted?
Yes
- Are you sending parameters to the activity through the bundle?
No
- Could you describe what are the actions do you make to raise that error?
see Description
- Android monitor shows any log related to the library when the error is shown?
Nothing
- Any other thing that could help me to reproduce the error?
"Bug" occurs on Android 7.0

## Screenshots
![screenshot_20170703-125835](https://user-images.githubusercontent.com/22591876/27790884-cb5517e6-5ff2-11e7-92e3-6405bd4d5898.png)

**Comment by sprengerst** [comment]
Any update on this?

**Comment by ferranpons** [comment]
@muellerch93 @sprengerst I'm going to check it. Please could you tell me which text did you use to reproduce it? And which locale are you using?

Thanks! And sorry for the inconvenience.

**Comment by ferranpons** [comment]
@muellerch93 @sprengerst I've found the issue and it's solved in the PR #107. After merging this PR I'll make a new release version. 😉

**Comment by muellerch93** [comment]
Nice
This would be an example of the problem:
If you search for "Vienna" it works just fine. If you search for "Wien" which is the german word for Vienna the place is located correctly but the check button is missing.
We are using:
.withSearchZone("de_DE") 
Thanks again for looking into it!

**Comment by ferranpons** [comment]
@muellerch93 new version 3.4.2 now available. Hope it solves your problem. If you're still experiencing this issue please reopen the issue.

Many thanks for your report!
