### ISSUE TITLE
Conflicting dependecies

### ISSUE THREAD

**Issue by ruha9005** [SchibstedSpain/Leku#99]
Please, update sdk tools versions to latest version 26 or exclude com.android.support libs from yoour project, because I can't use this module with my apps target sdk = 26;
Gradle build error code:
`Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(25.3.1) from [com.android.support:design:25.3.1] AndroidManifest.xml:27:9-31
	is also present at [com.android.support:appcompat-v7:26.0.0-alpha1] AndroidManifest.xml:27:9-38 value=(26.0.0-alpha1).
	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:25:5-27:34 to override.`

**Comment by ferranpons** [comment]
@ruha9005 until it's not supported on an stable AS version and it's not an alpha it will not be supported by us.

**Comment by ferranpons** [comment]
@ruha9005 We've just published a new version of the library that solves the issue. (v3.6.0)

Many thanks for reporting it and for your patience!
